sheet = "统计表"
name = "统计表"
start_col = "A"
query = """\
select lxr,zx,
sum(iif(sfwc in('1-已编写初稿','2-已提交需求/确认需规'),1,0)),       -- 已完成需求
sum(iif(sfwc in('3-已完成开发','4-已完成验收测试'),1,0)),       -- 开发中
sum(iif(sfwc = '5-已投产' ,1,0)) ,       -- 已投产
count(jym) as zs         -- 总数
from xmjh
where ywbm='运营管理部' and fa not in('1-下架交易','5-移出柜面系统')
group by zx,lxr
order by zs desc\
"""

[[column]]
name = "联系人"
total_string = "合计"

[[column]]
name = "中心"

[[column]]
name = "已完成需求"
format = "Number"
total_function = "sum"

[[column]]
name = "开发中"
format = "Number"
total_function = "sum"

[[column]]
name = "已投产"
format = "Number"
total_function = "sum"

[[column]]
name = "总数"
format = "Number"
total_function = "sum"

[[column]]
name = "投产完成率"
format = "Percent"
formula = "[已投产]/[总数]"
total_function = "统计表[[#Totals],[已投产]]/统计表[[#Totals],[总数]]"
